# -*- coding: utf-8 -*-
"""checkpoint18.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1d2gr6un_Sh3znDFtup4UBwM8axdln4dD
"""

import tensorflow_datasets as tfds

dataset, info = tfds.load(
    "cats_vs_dogs",
    as_supervised=True,
    with_info=True
)

from google.colab import drive
drive.mount('/content/drive')

train_ds, val_ds = tfds.load(
    "cats_vs_dogs",
    split=["train[:80%]", "train[80%:]"],
    as_supervised=True
)

import tensorflow as tf
from tensorflow.keras.applications.resnet50 import preprocess_input
IMG_SIZE = 224
BATCH_SIZE = 32



def preprocess(image, label):
    image = tf.image.resize(image, (224, 224))
    image = preprocess_input(image)
    return image, label


train_ds = train_ds.map(preprocess).shuffle(1000).batch(BATCH_SIZE)
val_ds = val_ds.map(preprocess).batch(BATCH_SIZE)

from tensorflow.keras.applications import ResNet50

base_model = ResNet50(
    weights="imagenet",
    include_top=False,
    input_shape=(224,224,3)
)

for layer in base_model.layers:
    layer.trainable = False

from tensorflow.keras import models, layers

model = models.Sequential([
    base_model,
    layers.GlobalAveragePooling2D(),
    layers.Dense(128, activation='relu'),
    layers.Dropout(0.5),
    layers.Dense(2, activation='softmax')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    train_ds,
    validation_data=val_ds,
    epochs=3
)

base_model.trainable = True

for layer in base_model.layers[:-20]:
    layer.trainable = False


model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=1e-5),
    loss="sparse_categorical_crossentropy",
    metrics=["accuracy"]
)

fine_tune_history = model.fit(train_ds,
                             epochs=3,
                             validation_data=val_ds)

model.save("animal_classifier.keras")

tf.__version__